.TH MYSTRCPY 3 "September 2026" "libmyutils" "Library Functions"

.SH NAME
mystrcpy \- copy a string into another string

.SH SYNOPSIS
.B #include "mystrfunctions.h"
.sp
.B int mystrcpy(char *dest, const char *src);

.SH DESCRIPTION
The
.B mystrcpy
function copies the string pointed to by
.BR src
into the character array pointed to by
.BR dest .
The terminating null character is also copied.

.SH AUTHOR
Iqra Saghir
iqra32388@gmail.com
